steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-golang:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/hello-golang:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --image=gcr.io/$PROJECT_ID/hello-golang:$SHORT_SHA
  - --app=hello-golang
  - --expose=8080
  - --location=asia-southeast2-a
  - --cluster=development-cluster