steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$BRANCH_NAME-hello-golang:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$BRANCH_NAME-hello-golang:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=deployment.yaml
  - --location=us-central1-b
  - --cluster=hello-cloudbuild
  env:
  - 'DOCKER_IMAGE=gcr.io/$PROJECT_ID/$BRANCH_NAME-hello-golang:$SHORT_SHA'