steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$BRANCH_NAME-hello-golang:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$BRANCH_NAME-hello-golang:$SHORT_SHA']
# This step generates the new manifest
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     sed "s/DOCKER_IMAGE/${IMAGE_NAME}/g" deployment.yaml
substitutions:
    IMAGE_NAME: gcr.io/$PROJECT_ID/$BRANCH_NAME-hello-golang:$SHORT_SHA
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=deployment.yaml
  - --location=us-central1-b
  - --cluster=hello-cloudbuild